ROLE_REQUIREMENTS = {
    "AI Engineer": [
        "python",
        "machine learning",
        "deep learning",
        "genai",
        "langchain",
        "rag",
        "vector databases",
        "fastapi",
        "cloud deployment",
    ],
    "Data Scientist": [
        "python",
        "sql",
        "statistics",
        "machine learning",
        "data visualization",
        "pandas",
        "numpy",
        "scikit-learn",
        "model evaluation",
    ],
    "ML Engineer": [
        "python",
        "machine learning",
        "deep learning",
        "mlops",
        "docker",
        "fastapi",
        "model deployment",
        "feature engineering",
        "cloud platforms",
    ],
    "Data Analyst": [
        "sql",
        "excel",
        "python",
        "statistics",
        "data visualization",
        "power bi",
        "tableau",
        "business analytics",
        "data cleaning",
    ],
    "Backend Developer": [
        "python",
        "fastapi",
        "sql",
        "rest api",
        "databases",
        "authentication",
        "docker",
        "testing",
        "system design",
    ],
}
